src/Symsite/Bundle/UploadFileBundle/Entity/UploadFile.php
<?php

namespace Symsite\Bundle\UploadFileBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symsite\Bundle\AdminBundle\Entity\BaseEntity;

/**
 * UploadFile
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Symsite\Bundle\UploadFileBundle\Entity\UploadFileRepository")
 * @ORM\HasLifecycleCallbacks
 */
class UploadFile extends BaseEntity
{
    const UPLOAD_PATH = 'uploads';

    private $root_path;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="extension", type="string", length=24, nullable=true)
     */
    private $extension;

    private $temp_path;

    /**
     * @var integer
     *
     * @ORM\Column(name="size", type="integer", nullable=true)
     */
    private $size;

    /**
     * @var UploadedFile
     *
     * @Assert\NotBlank()
     * @Assert\File(
     *      maxSize="1024k",
     *      mimeTypes={
     *          "application/pdf",
     *          "application/x-pdf",
     *          "image/gif",
     *          "image/jpeg",
     *          "image/png",
     *      }
     * )
     */
    private $file;

    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (is_file($this->getAbsolutePath())) {
            // store the old file path to delete after the update
            $this->temp_path = $this->getAbsolutePath();
        }
        $this->extension = null;
    }

    /**
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if (null !== $this->getFile()) {
            $this->extension = $this->getFile()->guessExtension();
            $this->size = $this->getFile()->getSize();
        }
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move(
          $this->getUploadRootDir(),
          $this->getFilename()
        );

        // check if we have an old image
        if (isset($this->temp_path)) {
            // delete the old image
            unlink($this->temp_path);
            $this->temp_path = null;
        }
        $this->file = null;
    }

    /**
     * @ORM\PreRemove()
     */
    public function storeFilePathForRemove()
    {
        $this->temp_path = $this->getAbsolutePath();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if (isset($this->temp_path)) {
            unlink($this->temp_path);
        }
    }

    public function getAbsolutePath()
    {
        return null === $this->extension ? null : $this->getUploadRootDir() . '/' . $this->getFilename();
    }

    public function getWebPath()
    {
        return null === $this->extension ? null : '/' . $this->getUploadDir() . '/' . $this->getFilename();
    }

    protected function getUploadRootDir()
    {
        return $this->root_path . '/web/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return UploadFile::UPLOAD_PATH;
    }

    public function getFilename()
    {
        return $this->id . '.' . $this->getExtension();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set extension
     *
     * @param string $extension
     *
     * @return UploadFile
     */
    public function setExtension($extension)
    {
        $this->extension = $extension;

        return $this;
    }

    /**
     * Get extension
     *
     * @return string
     */
    public function getExtension()
    {
        return $this->extension;
    }

    /**
     * Set size
     *
     * @param integer $size
     *
     * @return UploadFile
     */
    public function setSize($size)
    {
        $this->size = $size;

        return $this;
    }

    /**
     * Get size
     *
     * @return integer
     */
    public function getSize()
    {
        return $this->size;
    }

    public function setRootPath($root_path)
    {
        $this->root_path = $root_path;
    }
}

src/Symsite/Bundle/UploadFileBundle/Form/UploadFileType.php
<?php

namespace Symsite\Bundle\UploadFileBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symsite\Bundle\UploadFileBundle\Entity\UploadFile;

class UploadFileType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file', 'file', [
                'label' => false,
                'error_bubbling' => true
            ])
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => UploadFile::class,
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'upload_file';
    }
}

src/Symsite/Bundle/UploadFileBundle/Controller/UploadFileController.php
<?php

namespace Symsite\Bundle\UploadFileBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Form\Form;
use Symsite\Bundle\UploadFileBundle\Entity\UploadFile;
use Symsite\Bundle\UploadFileBundle\Form\UploadFileType;

class UploadFileController extends Controller
{
    /**
     * @Route("/upload_files", name="upload_files")
     * @Method({"GET", "POST"})
     */
    public function indexAction(Request $request)
    {
        $upload_file = new UploadFile();
        $form = $this->createForm(new UploadFileType(), $upload_file, [
          'action' => $this->generateUrl('upload_files'),
          'method' => 'POST'
        ]);

        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
            $this->createUploadFile($form, $upload_file);
        }

        $page = (int)$request->query->get('page', 1);
        $sortKey = $request->query->get('sort', 'u.createdAt');
        $direction = $request->query->get('direction', 'desc');

        $qb = $this->getDoctrine()->getRepository(UploadFile::class)
            ->createQueryBuilder('u')
            ->orderBy($sortKey, $direction);

        $entities = $this->get('knp_paginator')->paginate($qb, $page, 12);

        return $this->render(
          '@SymsiteUploadFile/UploadFile/index.html.twig',
          ['entities' => $entities, 'form' => $form->createView()]
        );
    }

    private function createUploadFile(Form $form, UploadFile $upload_file)
    {
        $t = $this->get('translator');

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($upload_file);
            $em->flush();

            $message = $t->trans('The file has been uploaded.');
            $this->addFlash('success', $message);
        } else {
            $message = $t->trans('The file could not be uploaded.');
            $this->addFlash('danger', $message);
        }
    }

    /**
     * @Route("/upload_files/api/upload", name="upload_files_api_upload")
     * @Method("POST")
     */
    public function uploadAction(Request $request)
    {
        $t = $this->get('translator');

        $upload_file = new UploadFile();
        $form = $this->createForm(new UploadFileType(), $upload_file);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($upload_file);
            $em->flush();

            return new Response($t->trans('The file has been uploaded.'), 200);
        }

        $message =  $t->trans('The file could not be uploaded.');
        if (count($form->getErrors()) > 0) {
            $message = $form->getErrors()[0]->getMessage();
        }

        return new Response($message, 400);
    }

    /**
     * @Route("/upload_files", name="upload_files_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request)
    {
        $delete_items = $request->request->get('delete_items');

        if (count($delete_items) > 0) {
            $em = $this->getDoctrine()->getManager();
            $upload_files = $em->getRepository(UploadFile::class)
                ->qbFindByIds($delete_items)
                ->getQuery()
                ->execute();

            $cnt = 0;
            foreach ($upload_files as $upload_file) {
                $em->remove($upload_file);
                $cnt++;
            }
            $em->flush();

            $t = $this->get('translator');
            $message = $t->trans('%count% %entity% has been deleted.', [
              '%count%' => $cnt,
              '%entity%' => $t->trans('File')
            ]);
            $this->addFlash('success', $message);
        }

        return $this->redirect($this->generateUrl('upload_files'));
    }
}

src/Symsite/Bundle/UploadFileBundle/Resources/views/UploadFile/index.html.twig
{% extends '@SymsiteAdmin/layout/base.html.twig' %}

{% block title %}Upload File{% endblock %}
{% block body_id %}uploadFileIndex{% endblock %}

{% block content %}
    <h1>{{ 'File'|trans }}</h1>
    <br/>
    <form id="deleteForm" action="{{ path('upload_files_delete') }}" method="post">
        <input type="hidden" name="_method" value="DELETE" />
    </form>
    <form id="myDropzone" class="dropzone" action="{{ path('upload_files_api_upload') }}">
        {{ form_widget(form._token) }}
    </form>
    {#{{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}#}
        {#{{ form_widget(form) }}#}
        {#<button type="submit"#}
                {#class="btn btn-primary"#}
                {#data-disable-with="{{ 'Processing...'|trans }}">{{ 'Upload'|trans }}</button>#}
    {#{{ form_end(form) }}#}

    {% if entities|length <= 0 %}
        <div class="spacer30">
            {{ '%entity% does not exist.'|trans({'%entity%': 'Media File'}) }}
        </div>
    {% else %}
        <div class="row spacer30">
            {% set cnt = 1 %}
            {% for entity in entities %}
                <div class="col-xs-6 col-sm-4 col-md-3">
                    <a href="{{ entity.webpath }}" class="thumbnail">
                        {% if entity.extension == 'pdf' %}
                            <img src="{{ asset('bundles/symsiteuploadfile/img/pdf.png') }}" alt="{{ entity.filename }}"/>
                        {% else %}
                            <img src="{{ entity.webpath }}" alt="{{ entity.filename }}"/>
                        {% endif %}
                    </a>
                    <div class="caption text-center">
                        <label>
                            <input type="checkbox" form="deleteForm" name="delete_items[]" value="{{ entity.id }}" class="checkDelete" />
                            <span class="fileName">{{ entity.filename }}</span><br/>
                            <div class="fileMeta">{{ entity.size|readable_filesize(0) }}</div>
                        </label>
                        <br/>
                    </div>
                </div>
                {% if (cnt % 2) == 0 %}
                    <div class="clearfix visible-xs-block"></div>
                {% endif %}
                {% if (cnt % 3) == 0 %}
                    <div class="clearfix visible-sm-block"></div>
                {% endif %}
                {% if (cnt % 4) == 0 %}
                    <div class="clearfix visible-md-block visible-lg-block"></div>
                {% endif %}
                {% set cnt = cnt + 1 %}
            {% endfor %}
        </div>

        {% include '@SymsiteAdmin/include/_index_nav.html.twig' with {
            'pagination': entities,
            'path': 'upload_files',
            'delete_form_id': 'deleteForm',
        } %}
    {% endif %}
{% endblock %}

{% block css %}
    {{ parent() }}
    <link rel="stylesheet" href="/bundles/symsiteadmin/bower_components/dropzone/dist/min/dropzone.min.css"/>
{% endblock %}

{% block script %}
    {{ parent() }}
    <script src="/bundles/symsiteadmin/bower_components/dropzone/dist/min/dropzone.min.js"></script>
    <script type="text/javascript">
        $(function(){
            Dropzone.options.myDropzone = {
                paramName: "upload_file[file]",
                maxFilesize: 1.024,
                acceptedFiles: "image/jpeg,image/png,image/gif,application/pdf",
                dictDefaultMessage: "Drop files here or click to upload."
            };
        });
    </script>
{% endblock %}